### ISSUE TITLE
Make events clickable

### ISSUE THREAD

**Issue by danyakarras** [danyakarras/Venue#2]
*can only be done after making table* (events_page.php)
AFTER filtering events in "Events", we go to a table of events in "event_page", and then each of these events should be clickable, to go to its own individual page

**Comment by ghost** [comment]
I have made event names clickable -  that will take you to a more detailed page about the event, and then another "buy my ticket" button that takes you to a confirmation page, which will add the customer, their ticketID etc into the db provided we have session management.
If we don't keep track of the session, we can't keep track of the cid and then we can't populate our tables which will be used by the managers. This is one of the issues that I'm not sure what to do about it. Have posted to piazza so we'll see
