### ISSUE TITLE
Pass information to venue page

### ISSUE THREAD

**Issue by danyakarras** [danyakarras/Venue#5]
When clicking button "Thrills" or any other venue name from the home page, the branchID should be sent to the "venue_page" so we know what page to set up. (home.php to venue_page.php)
(That is, we're not going to make 5 different pages for each venue, we're just gonna make one page, and populate it will all the right info based on the branchID that we pass it)

*This will be the same for when we click on an individual event and need to go to it's event page!!! So solving this helps a lot*

**Comment by ghost** [comment]
Yup, done.
